### ISSUE TITLE
create a walkthrough

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/vcpkg.nuget#3]
It would be valuable to do a brief video of how to leverage this in your own project.

**Comment by parkertomatoes** [comment]
A walkthrough would be wonderful. I'd really love to get this to work because I've got teammates who don't like being asked to manually install dependencies.

However, as a novice to this stuff, I can't figure out where the <VcpkgPackage> elements are supposed to go. I've thrown them all over my vcxproj file and I either get a parse error or a build error saying "the VcpkgPackage task was not found".

**Comment by bengreenier** [comment]
@parkertomatoes ah sorry about that. here's the quick version:

1) install nuget package using visual studio's "manage nuget packages" ui
2) right click your project and choose unload
3) right click the now unloaded project and choose edit
4) scroll to the bottom and add `<VcpkgPackage Include="packageName"/>` replacing `packageName` with the vcpkg port
5) repeat step 4 as needed
6) right click your project and choose reload
7) perform a build, notice that the build output will contain "running vcpkg" and vcpkg output

I'll try to make some time soon to create a simple template project that can be used as a reference. 🚀

**Comment by parkertomatoes** [comment]
Works perfectly now, thank you so much!

**Comment by bengreenier** [comment]
see https://github.com/bengreenier/vcpkg.nuget-example
